# Generated by Django 5.1.2 on 2024-12-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itech_solutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
