# Generated by Django 5.1.2 on 2024-12-25 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itech_solutions', '0002_remove_software_uploaded_at_alter_software_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
